blank_issues_enabled: false
contact_links:
  - name: 📧 No GitHub account? / Нет аккаунта GitHub?
    url: mailto:samoilov.oleg@icloud.com
    about: Send feedback by email instead / Отправьте отзыв письмом
